/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGudangRouteImport } from './routes/_app.gudang'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppMarketplaceMappingRouteImport } from './routes/_app.marketplace-mapping'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppPenggunaRouteImport } from './routes/_app.pengguna'
import { Route as AppPesananRouteImport } from './routes/_app.pesanan'
import { Route as AppProdukRouteImport } from './routes/_app.produk'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSinkronisasiRouteImport } from './routes/_app.sinkronisasi'
import { Route as AppStokRouteImport } from './routes/_app.stok'
import { Route as AppGudangIndexRouteImport } from './routes/_app.gudang.index'
import { Route as AppGudangPenambahanStokRouteImport } from './routes/_app.gudang.penambahan-stok'
import { Route as AppGudangPenguranganStokRouteImport } from './routes/_app.gudang.pengurangan-stok'
import { Route as AppGudangRincianStokRouteImport } from './routes/_app.gudang.rincian-stok'
import { Route as AppGudangRiwayatStokRouteImport } from './routes/_app.gudang.riwayat-stok'
import { Route as AppGudangStockOpnameRouteImport } from './routes/_app.gudang.stock-opname'
import { Route as AppLaporanIndexRouteImport } from './routes/_app.laporan.index'
import { Route as AppLaporanAnalisaBisnisRouteImport } from './routes/_app.laporan.analisa-bisnis'
import { Route as AppLaporanAnalisaKeuntunganRouteImport } from './routes/_app.laporan.analisa-keuntungan'
import { Route as AppMarketplaceMappingIndexRouteImport } from './routes/_app.marketplace-mapping.index'
import { Route as AppMarketplaceIndexRouteImport } from './routes/_app.marketplace.index'
import { Route as AppMarketplaceMarketplaceRouteImport } from './routes/_app.marketplace.$marketplace'
import { Route as AppPesananIndexRouteImport } from './routes/_app.pesanan.index'
import { Route as AppPesananDibatalkanRouteImport } from './routes/_app.pesanan.dibatalkan'
import { Route as AppPesananDikirimRouteImport } from './routes/_app.pesanan.dikirim'
import { Route as AppPesananMenungguDicetakRouteImport } from './routes/_app.pesanan.menunggu-dicetak'
import { Route as AppPesananMenungguDiprosesRouteImport } from './routes/_app.pesanan.menunggu-diproses'
import { Route as AppPesananMenungguPickupRouteImport } from './routes/_app.pesanan.menunggu-pickup'
import { Route as AppPesananScanKirimRouteImport } from './routes/_app.pesanan.scan-kirim'
import { Route as AppPesananSelesaiRouteImport } from './routes/_app.pesanan.selesai'
import { Route as AppProdukIndexRouteImport } from './routes/_app.produk.index'
import { Route as AppProdukArsipRouteImport } from './routes/_app.produk.arsip'
import { Route as AppProdukDraftRouteImport } from './routes/_app.produk.draft'
import { Route as AppProdukTambahRouteImport } from './routes/_app.produk.tambah'
import { Route as AppMarketplaceMappingShopeeIndexRouteImport } from './routes/_app.marketplace-mapping.shopee.index'
import { Route as AppMarketplaceMappingShopeeHubungkanRouteImport } from './routes/_app.marketplace-mapping.shopee.hubungkan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGudangRoute = AppGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceMappingRoute = AppMarketplaceMappingRouteImport.update({
  id: '/marketplace-mapping',
  path: '/marketplace-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPenggunaRoute = AppPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AppRoute,
} as any)
const AppPesananRoute = AppPesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => AppRoute,
} as any)
const AppProdukRoute = AppProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSinkronisasiRoute = AppSinkronisasiRouteImport.update({
  id: '/sinkronisasi',
  path: '/sinkronisasi',
  getParentRoute: () => AppRoute,
} as any)
const AppStokRoute = AppStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppRoute,
} as any)
const AppGudangIndexRoute = AppGudangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGudangRoute,
} as any)
const AppGudangPenambahanStokRoute = AppGudangPenambahanStokRouteImport.update({
  id: '/penambahan-stok',
  path: '/penambahan-stok',
  getParentRoute: () => AppGudangRoute,
} as any)
const AppGudangPenguranganStokRoute =
  AppGudangPenguranganStokRouteImport.update({
    id: '/pengurangan-stok',
    path: '/pengurangan-stok',
    getParentRoute: () => AppGudangRoute,
  } as any)
const AppGudangRincianStokRoute = AppGudangRincianStokRouteImport.update({
  id: '/rincian-stok',
  path: '/rincian-stok',
  getParentRoute: () => AppGudangRoute,
} as any)
const AppGudangRiwayatStokRoute = AppGudangRiwayatStokRouteImport.update({
  id: '/riwayat-stok',
  path: '/riwayat-stok',
  getParentRoute: () => AppGudangRoute,
} as any)
const AppGudangStockOpnameRoute = AppGudangStockOpnameRouteImport.update({
  id: '/stock-opname',
  path: '/stock-opname',
  getParentRoute: () => AppGudangRoute,
} as any)
const AppLaporanIndexRoute = AppLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLaporanRoute,
} as any)
const AppLaporanAnalisaBisnisRoute = AppLaporanAnalisaBisnisRouteImport.update({
  id: '/analisa-bisnis',
  path: '/analisa-bisnis',
  getParentRoute: () => AppLaporanRoute,
} as any)
const AppLaporanAnalisaKeuntunganRoute =
  AppLaporanAnalisaKeuntunganRouteImport.update({
    id: '/analisa-keuntungan',
    path: '/analisa-keuntungan',
    getParentRoute: () => AppLaporanRoute,
  } as any)
const AppMarketplaceMappingIndexRoute =
  AppMarketplaceMappingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppMarketplaceMappingRoute,
  } as any)
const AppMarketplaceIndexRoute = AppMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceMarketplaceRoute =
  AppMarketplaceMarketplaceRouteImport.update({
    id: '/marketplace/$marketplace',
    path: '/marketplace/$marketplace',
    getParentRoute: () => AppRoute,
  } as any)
const AppPesananIndexRoute = AppPesananIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPesananRoute,
} as any)
const AppPesananDibatalkanRoute = AppPesananDibatalkanRouteImport.update({
  id: '/dibatalkan',
  path: '/dibatalkan',
  getParentRoute: () => AppPesananRoute,
} as any)
const AppPesananDikirimRoute = AppPesananDikirimRouteImport.update({
  id: '/dikirim',
  path: '/dikirim',
  getParentRoute: () => AppPesananRoute,
} as any)
const AppPesananMenungguDicetakRoute =
  AppPesananMenungguDicetakRouteImport.update({
    id: '/menunggu-dicetak',
    path: '/menunggu-dicetak',
    getParentRoute: () => AppPesananRoute,
  } as any)
const AppPesananMenungguDiprosesRoute =
  AppPesananMenungguDiprosesRouteImport.update({
    id: '/menunggu-diproses',
    path: '/menunggu-diproses',
    getParentRoute: () => AppPesananRoute,
  } as any)
const AppPesananMenungguPickupRoute =
  AppPesananMenungguPickupRouteImport.update({
    id: '/menunggu-pickup',
    path: '/menunggu-pickup',
    getParentRoute: () => AppPesananRoute,
  } as any)
const AppPesananScanKirimRoute = AppPesananScanKirimRouteImport.update({
  id: '/scan-kirim',
  path: '/scan-kirim',
  getParentRoute: () => AppPesananRoute,
} as any)
const AppPesananSelesaiRoute = AppPesananSelesaiRouteImport.update({
  id: '/selesai',
  path: '/selesai',
  getParentRoute: () => AppPesananRoute,
} as any)
const AppProdukIndexRoute = AppProdukIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProdukRoute,
} as any)
const AppProdukArsipRoute = AppProdukArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => AppProdukRoute,
} as any)
const AppProdukDraftRoute = AppProdukDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => AppProdukRoute,
} as any)
const AppProdukTambahRoute = AppProdukTambahRouteImport.update({
  id: '/tambah',
  path: '/tambah',
  getParentRoute: () => AppProdukRoute,
} as any)
const AppMarketplaceMappingShopeeIndexRoute =
  AppMarketplaceMappingShopeeIndexRouteImport.update({
    id: '/shopee/',
    path: '/shopee/',
    getParentRoute: () => AppMarketplaceMappingRoute,
  } as any)
const AppMarketplaceMappingShopeeHubungkanRoute =
  AppMarketplaceMappingShopeeHubungkanRouteImport.update({
    id: '/shopee/hubungkan',
    path: '/shopee/hubungkan',
    getParentRoute: () => AppMarketplaceMappingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/gudang': typeof AppGudangRouteWithChildren
  '/laporan': typeof AppLaporanRouteWithChildren
  '/marketplace-mapping': typeof AppMarketplaceMappingRouteWithChildren
  '/pengaturan': typeof AppPengaturanRoute
  '/pengguna': typeof AppPenggunaRoute
  '/pesanan': typeof AppPesananRouteWithChildren
  '/produk': typeof AppProdukRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/sinkronisasi': typeof AppSinkronisasiRoute
  '/stok': typeof AppStokRoute
  '/gudang/penambahan-stok': typeof AppGudangPenambahanStokRoute
  '/gudang/pengurangan-stok': typeof AppGudangPenguranganStokRoute
  '/gudang/rincian-stok': typeof AppGudangRincianStokRoute
  '/gudang/riwayat-stok': typeof AppGudangRiwayatStokRoute
  '/gudang/stock-opname': typeof AppGudangStockOpnameRoute
  '/laporan/analisa-bisnis': typeof AppLaporanAnalisaBisnisRoute
  '/laporan/analisa-keuntungan': typeof AppLaporanAnalisaKeuntunganRoute
  '/marketplace/$marketplace': typeof AppMarketplaceMarketplaceRoute
  '/pesanan/dibatalkan': typeof AppPesananDibatalkanRoute
  '/pesanan/dikirim': typeof AppPesananDikirimRoute
  '/pesanan/menunggu-dicetak': typeof AppPesananMenungguDicetakRoute
  '/pesanan/menunggu-diproses': typeof AppPesananMenungguDiprosesRoute
  '/pesanan/menunggu-pickup': typeof AppPesananMenungguPickupRoute
  '/pesanan/scan-kirim': typeof AppPesananScanKirimRoute
  '/pesanan/selesai': typeof AppPesananSelesaiRoute
  '/produk/arsip': typeof AppProdukArsipRoute
  '/produk/draft': typeof AppProdukDraftRoute
  '/produk/tambah': typeof AppProdukTambahRoute
  '/gudang/': typeof AppGudangIndexRoute
  '/laporan/': typeof AppLaporanIndexRoute
  '/marketplace-mapping/': typeof AppMarketplaceMappingIndexRoute
  '/marketplace/': typeof AppMarketplaceIndexRoute
  '/pesanan/': typeof AppPesananIndexRoute
  '/produk/': typeof AppProdukIndexRoute
  '/marketplace-mapping/shopee/hubungkan': typeof AppMarketplaceMappingShopeeHubungkanRoute
  '/marketplace-mapping/shopee/': typeof AppMarketplaceMappingShopeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/pengguna': typeof AppPenggunaRoute
  '/profile': typeof AppProfileRoute
  '/sinkronisasi': typeof AppSinkronisasiRoute
  '/stok': typeof AppStokRoute
  '/gudang/penambahan-stok': typeof AppGudangPenambahanStokRoute
  '/gudang/pengurangan-stok': typeof AppGudangPenguranganStokRoute
  '/gudang/rincian-stok': typeof AppGudangRincianStokRoute
  '/gudang/riwayat-stok': typeof AppGudangRiwayatStokRoute
  '/gudang/stock-opname': typeof AppGudangStockOpnameRoute
  '/laporan/analisa-bisnis': typeof AppLaporanAnalisaBisnisRoute
  '/laporan/analisa-keuntungan': typeof AppLaporanAnalisaKeuntunganRoute
  '/marketplace/$marketplace': typeof AppMarketplaceMarketplaceRoute
  '/pesanan/dibatalkan': typeof AppPesananDibatalkanRoute
  '/pesanan/dikirim': typeof AppPesananDikirimRoute
  '/pesanan/menunggu-dicetak': typeof AppPesananMenungguDicetakRoute
  '/pesanan/menunggu-diproses': typeof AppPesananMenungguDiprosesRoute
  '/pesanan/menunggu-pickup': typeof AppPesananMenungguPickupRoute
  '/pesanan/scan-kirim': typeof AppPesananScanKirimRoute
  '/pesanan/selesai': typeof AppPesananSelesaiRoute
  '/produk/arsip': typeof AppProdukArsipRoute
  '/produk/draft': typeof AppProdukDraftRoute
  '/produk/tambah': typeof AppProdukTambahRoute
  '/gudang': typeof AppGudangIndexRoute
  '/laporan': typeof AppLaporanIndexRoute
  '/marketplace-mapping': typeof AppMarketplaceMappingIndexRoute
  '/marketplace': typeof AppMarketplaceIndexRoute
  '/pesanan': typeof AppPesananIndexRoute
  '/produk': typeof AppProdukIndexRoute
  '/marketplace-mapping/shopee/hubungkan': typeof AppMarketplaceMappingShopeeHubungkanRoute
  '/marketplace-mapping/shopee': typeof AppMarketplaceMappingShopeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gudang': typeof AppGudangRouteWithChildren
  '/_app/laporan': typeof AppLaporanRouteWithChildren
  '/_app/marketplace-mapping': typeof AppMarketplaceMappingRouteWithChildren
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/pengguna': typeof AppPenggunaRoute
  '/_app/pesanan': typeof AppPesananRouteWithChildren
  '/_app/produk': typeof AppProdukRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/sinkronisasi': typeof AppSinkronisasiRoute
  '/_app/stok': typeof AppStokRoute
  '/_app/gudang/penambahan-stok': typeof AppGudangPenambahanStokRoute
  '/_app/gudang/pengurangan-stok': typeof AppGudangPenguranganStokRoute
  '/_app/gudang/rincian-stok': typeof AppGudangRincianStokRoute
  '/_app/gudang/riwayat-stok': typeof AppGudangRiwayatStokRoute
  '/_app/gudang/stock-opname': typeof AppGudangStockOpnameRoute
  '/_app/laporan/analisa-bisnis': typeof AppLaporanAnalisaBisnisRoute
  '/_app/laporan/analisa-keuntungan': typeof AppLaporanAnalisaKeuntunganRoute
  '/_app/marketplace/$marketplace': typeof AppMarketplaceMarketplaceRoute
  '/_app/pesanan/dibatalkan': typeof AppPesananDibatalkanRoute
  '/_app/pesanan/dikirim': typeof AppPesananDikirimRoute
  '/_app/pesanan/menunggu-dicetak': typeof AppPesananMenungguDicetakRoute
  '/_app/pesanan/menunggu-diproses': typeof AppPesananMenungguDiprosesRoute
  '/_app/pesanan/menunggu-pickup': typeof AppPesananMenungguPickupRoute
  '/_app/pesanan/scan-kirim': typeof AppPesananScanKirimRoute
  '/_app/pesanan/selesai': typeof AppPesananSelesaiRoute
  '/_app/produk/arsip': typeof AppProdukArsipRoute
  '/_app/produk/draft': typeof AppProdukDraftRoute
  '/_app/produk/tambah': typeof AppProdukTambahRoute
  '/_app/gudang/': typeof AppGudangIndexRoute
  '/_app/laporan/': typeof AppLaporanIndexRoute
  '/_app/marketplace-mapping/': typeof AppMarketplaceMappingIndexRoute
  '/_app/marketplace/': typeof AppMarketplaceIndexRoute
  '/_app/pesanan/': typeof AppPesananIndexRoute
  '/_app/produk/': typeof AppProdukIndexRoute
  '/_app/marketplace-mapping/shopee/hubungkan': typeof AppMarketplaceMappingShopeeHubungkanRoute
  '/_app/marketplace-mapping/shopee/': typeof AppMarketplaceMappingShopeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/gudang'
    | '/laporan'
    | '/marketplace-mapping'
    | '/pengaturan'
    | '/pengguna'
    | '/pesanan'
    | '/produk'
    | '/profile'
    | '/sinkronisasi'
    | '/stok'
    | '/gudang/penambahan-stok'
    | '/gudang/pengurangan-stok'
    | '/gudang/rincian-stok'
    | '/gudang/riwayat-stok'
    | '/gudang/stock-opname'
    | '/laporan/analisa-bisnis'
    | '/laporan/analisa-keuntungan'
    | '/marketplace/$marketplace'
    | '/pesanan/dibatalkan'
    | '/pesanan/dikirim'
    | '/pesanan/menunggu-dicetak'
    | '/pesanan/menunggu-diproses'
    | '/pesanan/menunggu-pickup'
    | '/pesanan/scan-kirim'
    | '/pesanan/selesai'
    | '/produk/arsip'
    | '/produk/draft'
    | '/produk/tambah'
    | '/gudang/'
    | '/laporan/'
    | '/marketplace-mapping/'
    | '/marketplace/'
    | '/pesanan/'
    | '/produk/'
    | '/marketplace-mapping/shopee/hubungkan'
    | '/marketplace-mapping/shopee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/pengaturan'
    | '/pengguna'
    | '/profile'
    | '/sinkronisasi'
    | '/stok'
    | '/gudang/penambahan-stok'
    | '/gudang/pengurangan-stok'
    | '/gudang/rincian-stok'
    | '/gudang/riwayat-stok'
    | '/gudang/stock-opname'
    | '/laporan/analisa-bisnis'
    | '/laporan/analisa-keuntungan'
    | '/marketplace/$marketplace'
    | '/pesanan/dibatalkan'
    | '/pesanan/dikirim'
    | '/pesanan/menunggu-dicetak'
    | '/pesanan/menunggu-diproses'
    | '/pesanan/menunggu-pickup'
    | '/pesanan/scan-kirim'
    | '/pesanan/selesai'
    | '/produk/arsip'
    | '/produk/draft'
    | '/produk/tambah'
    | '/gudang'
    | '/laporan'
    | '/marketplace-mapping'
    | '/marketplace'
    | '/pesanan'
    | '/produk'
    | '/marketplace-mapping/shopee/hubungkan'
    | '/marketplace-mapping/shopee'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/gudang'
    | '/_app/laporan'
    | '/_app/marketplace-mapping'
    | '/_app/pengaturan'
    | '/_app/pengguna'
    | '/_app/pesanan'
    | '/_app/produk'
    | '/_app/profile'
    | '/_app/sinkronisasi'
    | '/_app/stok'
    | '/_app/gudang/penambahan-stok'
    | '/_app/gudang/pengurangan-stok'
    | '/_app/gudang/rincian-stok'
    | '/_app/gudang/riwayat-stok'
    | '/_app/gudang/stock-opname'
    | '/_app/laporan/analisa-bisnis'
    | '/_app/laporan/analisa-keuntungan'
    | '/_app/marketplace/$marketplace'
    | '/_app/pesanan/dibatalkan'
    | '/_app/pesanan/dikirim'
    | '/_app/pesanan/menunggu-dicetak'
    | '/_app/pesanan/menunggu-diproses'
    | '/_app/pesanan/menunggu-pickup'
    | '/_app/pesanan/scan-kirim'
    | '/_app/pesanan/selesai'
    | '/_app/produk/arsip'
    | '/_app/produk/draft'
    | '/_app/produk/tambah'
    | '/_app/gudang/'
    | '/_app/laporan/'
    | '/_app/marketplace-mapping/'
    | '/_app/marketplace/'
    | '/_app/pesanan/'
    | '/_app/produk/'
    | '/_app/marketplace-mapping/shopee/hubungkan'
    | '/_app/marketplace-mapping/shopee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gudang': {
      id: '/_app/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof AppGudangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace-mapping': {
      id: '/_app/marketplace-mapping'
      path: '/marketplace-mapping'
      fullPath: '/marketplace-mapping'
      preLoaderRoute: typeof AppMarketplaceMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengguna': {
      id: '/_app/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AppPenggunaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan': {
      id: '/_app/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof AppPesananRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produk': {
      id: '/_app/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof AppProdukRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sinkronisasi': {
      id: '/_app/sinkronisasi'
      path: '/sinkronisasi'
      fullPath: '/sinkronisasi'
      preLoaderRoute: typeof AppSinkronisasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok': {
      id: '/_app/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AppStokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gudang/': {
      id: '/_app/gudang/'
      path: '/'
      fullPath: '/gudang/'
      preLoaderRoute: typeof AppGudangIndexRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/gudang/penambahan-stok': {
      id: '/_app/gudang/penambahan-stok'
      path: '/penambahan-stok'
      fullPath: '/gudang/penambahan-stok'
      preLoaderRoute: typeof AppGudangPenambahanStokRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/gudang/pengurangan-stok': {
      id: '/_app/gudang/pengurangan-stok'
      path: '/pengurangan-stok'
      fullPath: '/gudang/pengurangan-stok'
      preLoaderRoute: typeof AppGudangPenguranganStokRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/gudang/rincian-stok': {
      id: '/_app/gudang/rincian-stok'
      path: '/rincian-stok'
      fullPath: '/gudang/rincian-stok'
      preLoaderRoute: typeof AppGudangRincianStokRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/gudang/riwayat-stok': {
      id: '/_app/gudang/riwayat-stok'
      path: '/riwayat-stok'
      fullPath: '/gudang/riwayat-stok'
      preLoaderRoute: typeof AppGudangRiwayatStokRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/gudang/stock-opname': {
      id: '/_app/gudang/stock-opname'
      path: '/stock-opname'
      fullPath: '/gudang/stock-opname'
      preLoaderRoute: typeof AppGudangStockOpnameRouteImport
      parentRoute: typeof AppGudangRoute
    }
    '/_app/laporan/': {
      id: '/_app/laporan/'
      path: '/'
      fullPath: '/laporan/'
      preLoaderRoute: typeof AppLaporanIndexRouteImport
      parentRoute: typeof AppLaporanRoute
    }
    '/_app/laporan/analisa-bisnis': {
      id: '/_app/laporan/analisa-bisnis'
      path: '/analisa-bisnis'
      fullPath: '/laporan/analisa-bisnis'
      preLoaderRoute: typeof AppLaporanAnalisaBisnisRouteImport
      parentRoute: typeof AppLaporanRoute
    }
    '/_app/laporan/analisa-keuntungan': {
      id: '/_app/laporan/analisa-keuntungan'
      path: '/analisa-keuntungan'
      fullPath: '/laporan/analisa-keuntungan'
      preLoaderRoute: typeof AppLaporanAnalisaKeuntunganRouteImport
      parentRoute: typeof AppLaporanRoute
    }
    '/_app/marketplace-mapping/': {
      id: '/_app/marketplace-mapping/'
      path: '/'
      fullPath: '/marketplace-mapping/'
      preLoaderRoute: typeof AppMarketplaceMappingIndexRouteImport
      parentRoute: typeof AppMarketplaceMappingRoute
    }
    '/_app/marketplace/': {
      id: '/_app/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AppMarketplaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace/$marketplace': {
      id: '/_app/marketplace/$marketplace'
      path: '/marketplace/$marketplace'
      fullPath: '/marketplace/$marketplace'
      preLoaderRoute: typeof AppMarketplaceMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan/': {
      id: '/_app/pesanan/'
      path: '/'
      fullPath: '/pesanan/'
      preLoaderRoute: typeof AppPesananIndexRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/dibatalkan': {
      id: '/_app/pesanan/dibatalkan'
      path: '/dibatalkan'
      fullPath: '/pesanan/dibatalkan'
      preLoaderRoute: typeof AppPesananDibatalkanRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/dikirim': {
      id: '/_app/pesanan/dikirim'
      path: '/dikirim'
      fullPath: '/pesanan/dikirim'
      preLoaderRoute: typeof AppPesananDikirimRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/menunggu-dicetak': {
      id: '/_app/pesanan/menunggu-dicetak'
      path: '/menunggu-dicetak'
      fullPath: '/pesanan/menunggu-dicetak'
      preLoaderRoute: typeof AppPesananMenungguDicetakRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/menunggu-diproses': {
      id: '/_app/pesanan/menunggu-diproses'
      path: '/menunggu-diproses'
      fullPath: '/pesanan/menunggu-diproses'
      preLoaderRoute: typeof AppPesananMenungguDiprosesRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/menunggu-pickup': {
      id: '/_app/pesanan/menunggu-pickup'
      path: '/menunggu-pickup'
      fullPath: '/pesanan/menunggu-pickup'
      preLoaderRoute: typeof AppPesananMenungguPickupRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/scan-kirim': {
      id: '/_app/pesanan/scan-kirim'
      path: '/scan-kirim'
      fullPath: '/pesanan/scan-kirim'
      preLoaderRoute: typeof AppPesananScanKirimRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/pesanan/selesai': {
      id: '/_app/pesanan/selesai'
      path: '/selesai'
      fullPath: '/pesanan/selesai'
      preLoaderRoute: typeof AppPesananSelesaiRouteImport
      parentRoute: typeof AppPesananRoute
    }
    '/_app/produk/': {
      id: '/_app/produk/'
      path: '/'
      fullPath: '/produk/'
      preLoaderRoute: typeof AppProdukIndexRouteImport
      parentRoute: typeof AppProdukRoute
    }
    '/_app/produk/arsip': {
      id: '/_app/produk/arsip'
      path: '/arsip'
      fullPath: '/produk/arsip'
      preLoaderRoute: typeof AppProdukArsipRouteImport
      parentRoute: typeof AppProdukRoute
    }
    '/_app/produk/draft': {
      id: '/_app/produk/draft'
      path: '/draft'
      fullPath: '/produk/draft'
      preLoaderRoute: typeof AppProdukDraftRouteImport
      parentRoute: typeof AppProdukRoute
    }
    '/_app/produk/tambah': {
      id: '/_app/produk/tambah'
      path: '/tambah'
      fullPath: '/produk/tambah'
      preLoaderRoute: typeof AppProdukTambahRouteImport
      parentRoute: typeof AppProdukRoute
    }
    '/_app/marketplace-mapping/shopee/': {
      id: '/_app/marketplace-mapping/shopee/'
      path: '/shopee'
      fullPath: '/marketplace-mapping/shopee/'
      preLoaderRoute: typeof AppMarketplaceMappingShopeeIndexRouteImport
      parentRoute: typeof AppMarketplaceMappingRoute
    }
    '/_app/marketplace-mapping/shopee/hubungkan': {
      id: '/_app/marketplace-mapping/shopee/hubungkan'
      path: '/shopee/hubungkan'
      fullPath: '/marketplace-mapping/shopee/hubungkan'
      preLoaderRoute: typeof AppMarketplaceMappingShopeeHubungkanRouteImport
      parentRoute: typeof AppMarketplaceMappingRoute
    }
  }
}

interface AppGudangRouteChildren {
  AppGudangPenambahanStokRoute: typeof AppGudangPenambahanStokRoute
  AppGudangPenguranganStokRoute: typeof AppGudangPenguranganStokRoute
  AppGudangRincianStokRoute: typeof AppGudangRincianStokRoute
  AppGudangRiwayatStokRoute: typeof AppGudangRiwayatStokRoute
  AppGudangStockOpnameRoute: typeof AppGudangStockOpnameRoute
  AppGudangIndexRoute: typeof AppGudangIndexRoute
}

const AppGudangRouteChildren: AppGudangRouteChildren = {
  AppGudangPenambahanStokRoute: AppGudangPenambahanStokRoute,
  AppGudangPenguranganStokRoute: AppGudangPenguranganStokRoute,
  AppGudangRincianStokRoute: AppGudangRincianStokRoute,
  AppGudangRiwayatStokRoute: AppGudangRiwayatStokRoute,
  AppGudangStockOpnameRoute: AppGudangStockOpnameRoute,
  AppGudangIndexRoute: AppGudangIndexRoute,
}

const AppGudangRouteWithChildren = AppGudangRoute._addFileChildren(
  AppGudangRouteChildren,
)

interface AppLaporanRouteChildren {
  AppLaporanAnalisaBisnisRoute: typeof AppLaporanAnalisaBisnisRoute
  AppLaporanAnalisaKeuntunganRoute: typeof AppLaporanAnalisaKeuntunganRoute
  AppLaporanIndexRoute: typeof AppLaporanIndexRoute
}

const AppLaporanRouteChildren: AppLaporanRouteChildren = {
  AppLaporanAnalisaBisnisRoute: AppLaporanAnalisaBisnisRoute,
  AppLaporanAnalisaKeuntunganRoute: AppLaporanAnalisaKeuntunganRoute,
  AppLaporanIndexRoute: AppLaporanIndexRoute,
}

const AppLaporanRouteWithChildren = AppLaporanRoute._addFileChildren(
  AppLaporanRouteChildren,
)

interface AppMarketplaceMappingRouteChildren {
  AppMarketplaceMappingIndexRoute: typeof AppMarketplaceMappingIndexRoute
  AppMarketplaceMappingShopeeHubungkanRoute: typeof AppMarketplaceMappingShopeeHubungkanRoute
  AppMarketplaceMappingShopeeIndexRoute: typeof AppMarketplaceMappingShopeeIndexRoute
}

const AppMarketplaceMappingRouteChildren: AppMarketplaceMappingRouteChildren = {
  AppMarketplaceMappingIndexRoute: AppMarketplaceMappingIndexRoute,
  AppMarketplaceMappingShopeeHubungkanRoute:
    AppMarketplaceMappingShopeeHubungkanRoute,
  AppMarketplaceMappingShopeeIndexRoute: AppMarketplaceMappingShopeeIndexRoute,
}

const AppMarketplaceMappingRouteWithChildren =
  AppMarketplaceMappingRoute._addFileChildren(
    AppMarketplaceMappingRouteChildren,
  )

interface AppPesananRouteChildren {
  AppPesananDibatalkanRoute: typeof AppPesananDibatalkanRoute
  AppPesananDikirimRoute: typeof AppPesananDikirimRoute
  AppPesananMenungguDicetakRoute: typeof AppPesananMenungguDicetakRoute
  AppPesananMenungguDiprosesRoute: typeof AppPesananMenungguDiprosesRoute
  AppPesananMenungguPickupRoute: typeof AppPesananMenungguPickupRoute
  AppPesananScanKirimRoute: typeof AppPesananScanKirimRoute
  AppPesananSelesaiRoute: typeof AppPesananSelesaiRoute
  AppPesananIndexRoute: typeof AppPesananIndexRoute
}

const AppPesananRouteChildren: AppPesananRouteChildren = {
  AppPesananDibatalkanRoute: AppPesananDibatalkanRoute,
  AppPesananDikirimRoute: AppPesananDikirimRoute,
  AppPesananMenungguDicetakRoute: AppPesananMenungguDicetakRoute,
  AppPesananMenungguDiprosesRoute: AppPesananMenungguDiprosesRoute,
  AppPesananMenungguPickupRoute: AppPesananMenungguPickupRoute,
  AppPesananScanKirimRoute: AppPesananScanKirimRoute,
  AppPesananSelesaiRoute: AppPesananSelesaiRoute,
  AppPesananIndexRoute: AppPesananIndexRoute,
}

const AppPesananRouteWithChildren = AppPesananRoute._addFileChildren(
  AppPesananRouteChildren,
)

interface AppProdukRouteChildren {
  AppProdukArsipRoute: typeof AppProdukArsipRoute
  AppProdukDraftRoute: typeof AppProdukDraftRoute
  AppProdukTambahRoute: typeof AppProdukTambahRoute
  AppProdukIndexRoute: typeof AppProdukIndexRoute
}

const AppProdukRouteChildren: AppProdukRouteChildren = {
  AppProdukArsipRoute: AppProdukArsipRoute,
  AppProdukDraftRoute: AppProdukDraftRoute,
  AppProdukTambahRoute: AppProdukTambahRoute,
  AppProdukIndexRoute: AppProdukIndexRoute,
}

const AppProdukRouteWithChildren = AppProdukRoute._addFileChildren(
  AppProdukRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGudangRoute: typeof AppGudangRouteWithChildren
  AppLaporanRoute: typeof AppLaporanRouteWithChildren
  AppMarketplaceMappingRoute: typeof AppMarketplaceMappingRouteWithChildren
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPenggunaRoute: typeof AppPenggunaRoute
  AppPesananRoute: typeof AppPesananRouteWithChildren
  AppProdukRoute: typeof AppProdukRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSinkronisasiRoute: typeof AppSinkronisasiRoute
  AppStokRoute: typeof AppStokRoute
  AppMarketplaceMarketplaceRoute: typeof AppMarketplaceMarketplaceRoute
  AppMarketplaceIndexRoute: typeof AppMarketplaceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGudangRoute: AppGudangRouteWithChildren,
  AppLaporanRoute: AppLaporanRouteWithChildren,
  AppMarketplaceMappingRoute: AppMarketplaceMappingRouteWithChildren,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPenggunaRoute: AppPenggunaRoute,
  AppPesananRoute: AppPesananRouteWithChildren,
  AppProdukRoute: AppProdukRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSinkronisasiRoute: AppSinkronisasiRoute,
  AppStokRoute: AppStokRoute,
  AppMarketplaceMarketplaceRoute: AppMarketplaceMarketplaceRoute,
  AppMarketplaceIndexRoute: AppMarketplaceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
